
help:           ## Show this help.
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'


cart:    ##intsall cart

	@sh components/cart.sh


cataloge: ##intsall cataloge
	@sh components/cataloge.sh


frontend: ##intsall frontend
	@sh components/frontend.sh



